In [2]:
import pandas as pd

In [7]:
body_data = pd.read_excel('C:/Users/Jayron/Documents/Mario_Triola/01 - Body Data.xlsx')

In [8]:
body_data

,AGE,GENDER (1=M),PULSE,SYSTOLIC,DIASTOLIC,HDL,LDL,WHITE,RED,PLATE,WEIGHT,HEIGHT,WAIST,ARM CIRC,BMI
0,43,0,80,100,70,73,68,8.7,4.80,319,98.6,172.0,120.4,40.7,33.3
1,57,1,84,112,70,35,116,4.9,4.73,187,96.9,186.0,107.8,37.0,28.0
2,38,0,94,134,94,36,223,6.9,4.47,297,108.2,154.4,120.3,44.3,45.4
3,80,1,74,126,64,37,83,7.5,4.32,170,73.1,160.5,97.2,30.3,28.4
4,34,1,50,114,68,50,104,6.1,4.95,140,83.1,179.0,95.1,34.0,25.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,24,1,94,96,62,43,102,7.0,5.29,260,56.3,162.7,78.4,27.9,21.3
296,50,0,94,132,84,42,69,7.9,4.35,244,103.2,146.7,142.6,39.5,48.0
297,53,1,86,132,74,42,112,8.4,4.07,75,102.6,181.0,117.7,36.5,31.3
298,34,0,74,104,54,44,103,7.6,4.36,292,96.1,162.2,109.0,37.0,36.5
299,31,1,90,104,70,64,112,6.0,5.07,197,56.4,165.4,74.0,26.5,20.6